export { default as Landing } from './Landing'
export { default as About } from './About'
export { default as Item } from './Item'
export { default as Newsletter } from './Newsletter'
export { default as HomeLayout } from './HomeLayout'
export { default as Error } from './Error'
export { default as SinglePageError } from './SinglePageError'
